### ISSUE TITLE
Multi line comment not working.

### ISSUE THREAD

**Issue by vidoss** [SamyPesse/slate-prism#4]
Since the decorator gets one text node at a time, multi-line comments with /* */ are not color coded as comments. Not sure how this can be fixed. Maybe marks should be applied as transform() onChange instead of plugin decorator. Any thoughts ?

**Comment by Soreine** [comment]
This problem does not exists if your code nodes contain a single text node, with newlines character inside.

However, that generally leads to poor performance when writing inside large code chunks. That's why in `slate-edit-code` we took the approach to split code in multiple line nodes. The problem with that approach is that Prism is not fed the whole text.

Maybe `slate-prism` could ask which code block each code line belongs to. The plugin would manage a dictionary of code blocks, code lines, and their texts, so that when it has to decorate a specific line, it has all the necessary context. I think the main performance bottleneck is not Prism itself, but the DOM operations of marks, so this could still be fast.

~~I don't know what would yield the use of marks. Maybe @SamyPesse had thought about it. I see one big downside though, that it affects the document data. `slate-prism` should ideally just have  rendering implications.~~

Edit: My bad. There's no concept of decorators in Slate. We use marks. I removed the irrelevant parts.

**Comment by ianstormtaylor** [comment]
@Soreine I think `slate-prism` could take an optional argument like `blockPerLine: true`, and then the `match` function of the decorator rule could match the container, and pass the `block.text` of the container to Prism, which would include all of the code lines. 

Then when applying the tokens to the, use `text.characters` still. And to keep performance, just retain a reference to the previous `block.text` and `tokens`, and if the text matches, just re-use the tokens, so you don't have to parse again for each line.

**Comment by Soreine** [comment]
Fixed by #5
